### PR TITLE
SERVER-62009 Initialize new private workload repo

### PR DESCRIPTION
**Pull request by dalyd**
This is just the first step. system-perf.yml change coming next, but I wanted to get the boiler plate taken care of.

### CODE REVIEW

**Comment by dalyd** [comment]
Also, just wanted to get eyes on this. Nothing deep so far, but if there's anything I'm missing, please give a shout.

**Review by rtimmons — APPROVED** [review]

**Review by aggrand — APPROVED** [review]

**Review by apodelko — APPROVED** [review]
LGTM. 

Is there a reason to run this HelloWorks on standalone all the time - or it is for test purposes and you plan to replace it real workloads in the future? Just double checking that I am not missing anything here.

**Comment by dalyd** [comment]
> LGTM.
> 
> Is there a reason to run this HelloWorks on standalone all the time - or it is for test purposes and you plan to replace it real workloads in the future? Just double checking that I am not missing anything here.

The latter. Just a simple workload to test out the functionality, separate from the real production work. Standalone is cheap, so contemplated a little just leaving it as a canary/smoke test.

**Comment by dalyd** [comment]
Updated PR. https://spruce.mongodb.com/task/sys_perf_task_generation_schedule_global_auto_tasks_patch_0220bb0c39c75858689c95d90e0c07e42773bf55_61ba5406850e6154483a9090_21_12_15_20_48_35/logs?execution=0

That one didn't work. Take 2: https://spruce.mongodb.com/task/sys_perf_task_generation_schedule_global_auto_tasks_patch_0220bb0c39c75858689c95d90e0c07e42773bf55_61ba5baec9ec4420e7f8d78c_21_12_15_21_19_26/logs?execution=0

**Comment by rtimmons** [comment]
David the base-revision for your latest patch is 0220bb0c39c75858689c95d90e0c07e42773bf55 which is old and thus has an older version of genny pinned.

**Comment by dalyd** [comment]
> https://spruce.mongodb.com/task/sys_perf_task_generation_schedule_global_auto_tasks_patch_0220bb0c39c75858689c95d90e0c07e42773bf55_61ba5406850e6154483a9090_21_12_15_20_48_35/logs?execution=0

You are right -- although I'm not sure how I managed that. I hit pull a bunch of times. Try number 3: https://evergreen.mongodb.com/patch/61bb4afd3627e04195c2c54e?redirect_spruce_users=true

**Comment by dalyd** [comment]
Working much better now. I'm going to run the generated task, but it shoudl be good now.

**Comment by rtimmons** [comment]
Ya seems fine now - I see 

```json
"auto_workload_path": "./src/PrivateWorkloads/src/workloads/examples/HelloWorld.yml"
```

in the generated task json.

**Comment by dalyd** [comment]
@rtimmons It definitely sees it, but my auto patch task didn't generate a new task. Any ideas?

**Comment by rtimmons** [comment]
> my auto patch task didn't generate a new task. Any ideas?

I think you need to schedule `variant_auto_tasks` although iiuc patch_auto_tasks should have noticed this as a changed workload yaml and should have automatically scheduled it regardless of the `AutoRun` section.

Beyond that I'd need to punt to TIPS to poke. The `schedule` tasks don't dump the expansions so it makes it harder to debug locally.

**Pull request merged**
